# fly.toml app configuration file generated for scradd-weathered-sunset-3636 on 2023-12-24T18:29:00-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrub"
primary_region = "iad"
kill_timeout = 60


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
