# fly.toml app configuration file generated for scratchblocks on 2024-06-26T20:46:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scratchblocks'
primary_region = 'iad'
kill_timeout = '1m0s'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
