# fly.toml app configuration file generated for scrub on 2024-01-13T18:41:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrub"
primary_region = "iad"
kill_timeout = "1m0s"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
